//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityReactionsTbl
    {
        public int Id { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> ReactionEmojiID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual HtmlEmojiTbl HtmlEmojiTbl { get; set; }
        public virtual TicketHistoryTbl TicketHistoryTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
