//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnVisibilityMainTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColumnVisibilityMainTbl()
        {
            this.ColumnVisibilityByUserTbl = new HashSet<ColumnVisibilityByUserTbl>();
        }
    
        public int Id { get; set; }
        public string TableColumnName { get; set; }
        public Nullable<int> TableColumnIndex { get; set; }
        public Nullable<bool> DefaultVisibility { get; set; }
        public string TableModelName { get; set; }
        public Nullable<bool> CustomerVisibility { get; set; }
        public Nullable<bool> AllTicketViewVisibility { get; set; }
        public string PageName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColumnVisibilityByUserTbl> ColumnVisibilityByUserTbl { get; set; }
    }
}
