//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnVisibilityByUserTbl
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ColumnNameID { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<int> ColumnIndex { get; set; }
    
        public virtual ColumnVisibilityMainTbl ColumnVisibilityMainTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
