//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentsTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommentsTbl()
        {
            this.CommentReactionsTbl = new HashSet<CommentReactionsTbl>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<bool> EditStatus { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> CustomerVisible { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public string CommentGuid { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string JiraSharedStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentReactionsTbl> CommentReactionsTbl { get; set; }
        public virtual MainTicketTbl MainTicketTbl { get; set; }
        public virtual UnitTbl UnitTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
