//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContexDB : DbContext
    {
        public ContexDB()
            : base("name=ContexDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityReactionsTbl> ActivityReactionsTbl { get; set; }
        public virtual DbSet<BTCostTbl> BTCostTbl { get; set; }
        public virtual DbSet<ColumnVisibilityByUserTbl> ColumnVisibilityByUserTbl { get; set; }
        public virtual DbSet<ColumnVisibilityMainTbl> ColumnVisibilityMainTbl { get; set; }
        public virtual DbSet<CommentReactionsTbl> CommentReactionsTbl { get; set; }
        public virtual DbSet<CommentsTbl> CommentsTbl { get; set; }
        public virtual DbSet<DefaultFilterTbl> DefaultFilterTbl { get; set; }
        public virtual DbSet<DeveloperUnitTbl> DeveloperUnitTbl { get; set; }
        public virtual DbSet<EmojiGroupTbl> EmojiGroupTbl { get; set; }
        public virtual DbSet<EmojiTbl> EmojiTbl { get; set; }
        public virtual DbSet<ExcelExportParametersList> ExcelExportParametersList { get; set; }
        public virtual DbSet<FilesTbl> FilesTbl { get; set; }
        public virtual DbSet<FilterCreateTBL> FilterCreateTBL { get; set; }
        public virtual DbSet<GroupTbl> GroupTbl { get; set; }
        public virtual DbSet<HtmlEmojiTbl> HtmlEmojiTbl { get; set; }
        public virtual DbSet<JiraComponentTbl> JiraComponentTbl { get; set; }
        public virtual DbSet<JiraKeyTbl> JiraKeyTbl { get; set; }
        public virtual DbSet<JiraUsersTbl> JiraUsersTbl { get; set; }
        public virtual DbSet<LogTbl> LogTbl { get; set; }
        public virtual DbSet<MailTypeTbl> MailTypeTbl { get; set; }
        public virtual DbSet<MainTicketTbl> MainTicketTbl { get; set; }
        public virtual DbSet<NotificationTbl> NotificationTbl { get; set; }
        public virtual DbSet<OperationRelTbl> OperationRelTbl { get; set; }
        public virtual DbSet<OperationTbl> OperationTbl { get; set; }
        public virtual DbSet<OutSourceUserInfoTbl> OutSourceUserInfoTbl { get; set; }
        public virtual DbSet<ParameterTbl> ParameterTbl { get; set; }
        public virtual DbSet<ProjectTbl> ProjectTbl { get; set; }
        public virtual DbSet<RoleTbl> RoleTbl { get; set; }
        public virtual DbSet<StatusFlowTbl> StatusFlowTbl { get; set; }
        public virtual DbSet<StatusLogTbl> StatusLogTbl { get; set; }
        public virtual DbSet<SuboperationTbl> SuboperationTbl { get; set; }
        public virtual DbSet<SystemProcessRoleTbl> SystemProcessRoleTbl { get; set; }
        public virtual DbSet<SystemProcessTbl> SystemProcessTbl { get; set; }
        public virtual DbSet<TicketComponentTbl> TicketComponentTbl { get; set; }
        public virtual DbSet<TicketDeveloperTbl> TicketDeveloperTbl { get; set; }
        public virtual DbSet<TicketHistoryTbl> TicketHistoryTbl { get; set; }
        public virtual DbSet<TicketInvoiceTbl> TicketInvoiceTbl { get; set; }
        public virtual DbSet<TicketJiraTbl> TicketJiraTbl { get; set; }
        public virtual DbSet<TicketParameterListTbl> TicketParameterListTbl { get; set; }
        public virtual DbSet<TicketParametertbl> TicketParametertbl { get; set; }
        public virtual DbSet<TicketPriorityTbl> TicketPriorityTbl { get; set; }
        public virtual DbSet<TicketResolutionTbl> TicketResolutionTbl { get; set; }
        public virtual DbSet<TicketStatusTbl> TicketStatusTbl { get; set; }
        public virtual DbSet<TicketTypeTbl> TicketTypeTbl { get; set; }
        public virtual DbSet<UnitTbl> UnitTbl { get; set; }
        public virtual DbSet<UserEmojiUsageTbl> UserEmojiUsageTbl { get; set; }
        public virtual DbSet<UserFilterTbl> UserFilterTbl { get; set; }
        public virtual DbSet<UserFollowerGroupListTbl> UserFollowerGroupListTbl { get; set; }
        public virtual DbSet<UserFollowerGroupTbl> UserFollowerGroupTbl { get; set; }
        public virtual DbSet<UserMailOptionTbl> UserMailOptionTbl { get; set; }
        public virtual DbSet<UserRoleTbl> UserRoleTbl { get; set; }
        public virtual DbSet<UserTbl> UserTbl { get; set; }
        public virtual DbSet<UserUnitTbl> UserUnitTbl { get; set; }
        public virtual DbSet<WatcherGroupTbl> WatcherGroupTbl { get; set; }
        public virtual DbSet<WatchersTbl> WatchersTbl { get; set; }
        public virtual DbSet<WebServiceLogTbl> WebServiceLogTbl { get; set; }
    }
}
