//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeveloperUnitTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeveloperUnitTbl()
        {
            this.MainTicketTbl = new HashSet<MainTicketTbl>();
            this.OutSourceUserInfoTbl = new HashSet<OutSourceUserInfoTbl>();
        }
    
        public int Id { get; set; }
        public string DeveloperUnit { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<bool> NotUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutSourceUserInfoTbl> OutSourceUserInfoTbl { get; set; }
    }
}
