//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmojiGroupTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmojiGroupTbl()
        {
            this.EmojiTbl = new HashSet<EmojiTbl>();
            this.HtmlEmojiTbl = new HashSet<HtmlEmojiTbl>();
        }
    
        public int Id { get; set; }
        public string EmojiGroupName { get; set; }
        public string GroupIconBase64 { get; set; }
        public string HtmlFontIcon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmojiTbl> EmojiTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HtmlEmojiTbl> HtmlEmojiTbl { get; set; }
    }
}
