//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmojiTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmojiTbl()
        {
            this.UserEmojiUsageTbl = new HashSet<UserEmojiUsageTbl>();
        }
    
        public int Id { get; set; }
        public string EmojiBase64 { get; set; }
        public string Name { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<int> EmojiGroupId { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<bool> FastAnswer { get; set; }
    
        public virtual EmojiGroupTbl EmojiGroupTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEmojiUsageTbl> UserEmojiUsageTbl { get; set; }
    }
}
