//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelExportParametersList
    {
        public int Id { get; set; }
        public string DatabaseColumnName { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public string ShownColumnName { get; set; }
        public Nullable<bool> CustomerVisibility { get; set; }
        public string PageName { get; set; }
    }
}
