//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesTbl
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FileFolderName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> AddedUserId { get; set; }
        public string FileGuid { get; set; }
        public Nullable<bool> CustomerVisibility { get; set; }
        public string JiraSharedStatus { get; set; }
        public string ThumbBase64 { get; set; }
    
        public virtual MainTicketTbl MainTicketTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
