//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterCreateTBL
    {
        public int id { get; set; }
        public string filterID { get; set; }
        public string filterName { get; set; }
        public Nullable<bool> isSelectableFilter { get; set; }
        public Nullable<bool> hasImage { get; set; }
        public Nullable<bool> hasIcon { get; set; }
        public Nullable<bool> nonListItemStatus { get; set; }
        public string nonListItemText { get; set; }
        public string sqlWhereClause { get; set; }
        public string PageName { get; set; }
        public Nullable<bool> isSpecialFilter { get; set; }
        public Nullable<int> orderNumber { get; set; }
    }
}
