//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlEmojiTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HtmlEmojiTbl()
        {
            this.ActivityReactionsTbl = new HashSet<ActivityReactionsTbl>();
            this.CommentReactionsTbl = new HashSet<CommentReactionsTbl>();
        }
    
        public int Id { get; set; }
        public string EmojiHtmlCode { get; set; }
        public string Name { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<int> EmojiGroupId { get; set; }
        public Nullable<int> OrdeNo { get; set; }
        public Nullable<bool> IsReaction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityReactionsTbl> ActivityReactionsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentReactionsTbl> CommentReactionsTbl { get; set; }
        public virtual EmojiGroupTbl EmojiGroupTbl { get; set; }
    }
}
