//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiraComponentTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JiraComponentTbl()
        {
            this.MainTicketTbl = new HashSet<MainTicketTbl>();
            this.TicketComponentTbl = new HashSet<TicketComponentTbl>();
        }
    
        public int Id { get; set; }
        public string Component { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<bool> IsJiraContains { get; set; }
        public Nullable<bool> NotComponent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketComponentTbl> TicketComponentTbl { get; set; }
    }
}
