//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiraUsersTbl
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string JiraKey { get; set; }
        public string DisplayName { get; set; }
        public string Html { get; set; }
    }
}
