//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTicketTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainTicketTbl()
        {
            this.CommentsTbl = new HashSet<CommentsTbl>();
            this.FilesTbl = new HashSet<FilesTbl>();
            this.MainTicketTbl1 = new HashSet<MainTicketTbl>();
            this.StatusLogTbl = new HashSet<StatusLogTbl>();
            this.TicketComponentTbl = new HashSet<TicketComponentTbl>();
            this.TicketDeveloperTbl = new HashSet<TicketDeveloperTbl>();
            this.TicketHistoryTbl = new HashSet<TicketHistoryTbl>();
            this.TicketInvoiceTbl = new HashSet<TicketInvoiceTbl>();
            this.TicketJiraTbl = new HashSet<TicketJiraTbl>();
            this.WatchersTbl = new HashSet<WatchersTbl>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Summary { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ResolutionId { get; set; }
        public Nullable<int> ReporterUserId { get; set; }
        public Nullable<int> RequestorId { get; set; }
        public Nullable<int> DeveloperUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string ResolutionDetail { get; set; }
        public string TaskGuid { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> CloserUserId { get; set; }
        public Nullable<int> CustomerStatusId { get; set; }
        public Nullable<System.DateTime> CustomerUpdatedDate { get; set; }
        public Nullable<bool> DeletedStatus { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> ManagerConfirmation { get; set; }
        public string Description { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
        public Nullable<int> TicketUnitId { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<bool> SubTaskState { get; set; }
        public Nullable<int> SubtaskMainTicketId { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<int> DeveloperUnitId { get; set; }
        public Nullable<int> AssigneeUserId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> AutoReject { get; set; }
        public Nullable<System.DateTime> APTransitionDate { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public string UploadFileName { get; set; }
        public Nullable<int> OpenedUserId { get; set; }
        public Nullable<System.DateTime> PlanningStartDate { get; set; }
        public Nullable<System.DateTime> PlaningEndDate { get; set; }
        public Nullable<System.DateTime> InProgressDate { get; set; }
        public Nullable<int> MainTicketId { get; set; }
        public Nullable<bool> TestCase { get; set; }
        public Nullable<int> TestMainTaskId { get; set; }
        public Nullable<bool> MainTestCase { get; set; }
        public Nullable<bool> ExternalTicket { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentsTbl> CommentsTbl { get; set; }
        public virtual DeveloperUnitTbl DeveloperUnitTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilesTbl> FilesTbl { get; set; }
        public virtual JiraComponentTbl JiraComponentTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl1 { get; set; }
        public virtual MainTicketTbl MainTicketTbl2 { get; set; }
        public virtual OutSourceUserInfoTbl OutSourceUserInfoTbl { get; set; }
        public virtual ProjectTbl ProjectTbl { get; set; }
        public virtual TicketPriorityTbl TicketPriorityTbl { get; set; }
        public virtual TicketResolutionTbl TicketResolutionTbl { get; set; }
        public virtual TicketStatusTbl TicketStatusTbl { get; set; }
        public virtual TicketStatusTbl TicketStatusTbl1 { get; set; }
        public virtual TicketTypeTbl TicketTypeTbl { get; set; }
        public virtual UnitTbl UnitTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
        public virtual UserTbl UserTbl1 { get; set; }
        public virtual UserTbl UserTbl2 { get; set; }
        public virtual UserTbl UserTbl3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusLogTbl> StatusLogTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketComponentTbl> TicketComponentTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketDeveloperTbl> TicketDeveloperTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketHistoryTbl> TicketHistoryTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketInvoiceTbl> TicketInvoiceTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketJiraTbl> TicketJiraTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WatchersTbl> WatchersTbl { get; set; }
    }
}
