//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationRelTbl
    {
        public int Id { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<int> OperationId { get; set; }
    
        public virtual OperationTbl OperationTbl { get; set; }
        public virtual SuboperationTbl SuboperationTbl { get; set; }
    }
}
