//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutSourceUserInfoTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OutSourceUserInfoTbl()
        {
            this.MainTicketTbl = new HashSet<MainTicketTbl>();
            this.TicketDeveloperTbl = new HashSet<TicketDeveloperTbl>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OutSourceCompanyId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<bool> NotDeveloper { get; set; }
    
        public virtual DeveloperUnitTbl DeveloperUnitTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketDeveloperTbl> TicketDeveloperTbl { get; set; }
    }
}
