//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleTbl()
        {
            this.SystemProcessRoleTbl = new HashSet<SystemProcessRoleTbl>();
            this.UserRoleTbl = new HashSet<UserRoleTbl>();
        }
    
        public int Id { get; set; }
        public string Role { get; set; }
        public Nullable<bool> DefaultRole { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<bool> SpecialRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemProcessRoleTbl> SystemProcessRoleTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleTbl> UserRoleTbl { get; set; }
    }
}
