//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusFlowTbl
    {
        public int Id { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> NextStatusId { get; set; }
        public Nullable<bool> CustomerVisible { get; set; }
        public Nullable<bool> SendMail { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<bool> OnlyAdmin { get; set; }
        public Nullable<bool> OnlyTester { get; set; }
        public Nullable<bool> CreateTestCase { get; set; }
        public Nullable<bool> OnlyMainTestCase { get; set; }
        public Nullable<bool> OnlyTestCases { get; set; }
        public Nullable<bool> MakeTestCasesDispose { get; set; }
    
        public virtual TicketStatusTbl TicketStatusTbl { get; set; }
        public virtual TicketStatusTbl TicketStatusTbl1 { get; set; }
    }
}
