//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusLogTbl
    {
        public int Id { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> LastStatusId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateMethod { get; set; }
        public Nullable<int> BeforeStatusId { get; set; }
        public Nullable<bool> CustomerVisible { get; set; }
    
        public virtual MainTicketTbl MainTicketTbl { get; set; }
        public virtual TicketStatusTbl TicketStatusTbl { get; set; }
        public virtual TicketStatusTbl TicketStatusTbl1 { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
