//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemProcessRoleTbl
    {
        public int Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
    
        public virtual RoleTbl RoleTbl { get; set; }
        public virtual SystemProcessTbl SystemProcessTbl { get; set; }
    }
}
