//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketHistoryTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketHistoryTbl()
        {
            this.ActivityReactionsTbl = new HashSet<ActivityReactionsTbl>();
            this.NotificationTbl = new HashSet<NotificationTbl>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string OperationDefinition { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string LogArea { get; set; }
        public Nullable<bool> CustomerVisibility { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string ChangeExplanation { get; set; }
        public Nullable<bool> IsStatusChange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityReactionsTbl> ActivityReactionsTbl { get; set; }
        public virtual MainTicketTbl MainTicketTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationTbl> NotificationTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
