//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDeveloperTbl
    {
        public int Id { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> DeveloperUserId { get; set; }
    
        public virtual MainTicketTbl MainTicketTbl { get; set; }
        public virtual OutSourceUserInfoTbl OutSourceUserInfoTbl { get; set; }
    }
}
