//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketPriorityTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketPriorityTbl()
        {
            this.MainTicketTbl = new HashSet<MainTicketTbl>();
        }
    
        public int Id { get; set; }
        public string PriortyDescription { get; set; }
        public Nullable<bool> SystemDefinition { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public string IconPath { get; set; }
        public string ShortPath { get; set; }
        public string PriorityBase64 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl { get; set; }
    }
}
