//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTypeTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketTypeTbl()
        {
            this.MainTicketTbl = new HashSet<MainTicketTbl>();
        }
    
        public int Id { get; set; }
        public string TypeDescription { get; set; }
        public string IconPath { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<bool> SystemDefinition { get; set; }
        public string ShortPath { get; set; }
        public Nullable<bool> NeedProjectName { get; set; }
        public Nullable<bool> NeedManagerApproval { get; set; }
        public Nullable<bool> CustomerVisible { get; set; }
        public Nullable<bool> NeedMainTicketId { get; set; }
        public string TypeBase64 { get; set; }
        public Nullable<bool> TestPlan { get; set; }
        public Nullable<bool> TestCase { get; set; }
        public Nullable<bool> TesterCan { get; set; }
        public Nullable<bool> JustQdevelop { get; set; }
        public Nullable<bool> AutoAssign { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl { get; set; }
    }
}
