//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketJiraTbl
    {
        public int Id { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string JiraID { get; set; }
        public Nullable<int> JiraKeyId { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> DeletedStatus { get; set; }
    
        public virtual JiraKeyTbl JiraKeyTbl { get; set; }
        public virtual MainTicketTbl MainTicketTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
