//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketStatusTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketStatusTbl()
        {
            this.MainTicketTbl = new HashSet<MainTicketTbl>();
            this.MainTicketTbl1 = new HashSet<MainTicketTbl>();
            this.StatusFlowTbl = new HashSet<StatusFlowTbl>();
            this.StatusFlowTbl1 = new HashSet<StatusFlowTbl>();
            this.StatusLogTbl = new HashSet<StatusLogTbl>();
            this.StatusLogTbl1 = new HashSet<StatusLogTbl>();
        }
    
        public int Id { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<bool> SystemDefinition { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public string BackgroundColor { get; set; }
        public string Definition { get; set; }
        public string FontColor { get; set; }
        public Nullable<bool> CustomerEditable { get; set; }
        public Nullable<bool> NecessaryExplanation { get; set; }
        public string TagName { get; set; }
        public Nullable<bool> UnresolvedStatus { get; set; }
        public string ActionText { get; set; }
        public string CompleteSentence { get; set; }
        public Nullable<int> CustomerStatusId { get; set; }
        public Nullable<bool> CustomerVisible { get; set; }
        public Nullable<bool> IsTestStatus { get; set; }
        public Nullable<bool> CheckTest { get; set; }
        public Nullable<bool> CheckComplite { get; set; }
        public Nullable<bool> CheckResolved { get; set; }
        public string ExpTitle { get; set; }
        public Nullable<bool> CheckAssignee { get; set; }
        public Nullable<bool> CheckTestPlanStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusFlowTbl> StatusFlowTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusFlowTbl> StatusFlowTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusLogTbl> StatusLogTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusLogTbl> StatusLogTbl1 { get; set; }
        public virtual TicketStatusTbl TicketStatusTbl1 { get; set; }
        public virtual TicketStatusTbl TicketStatusTbl2 { get; set; }
    }
}
