//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTbl()
        {
            this.ActivityReactionsTbl = new HashSet<ActivityReactionsTbl>();
            this.ColumnVisibilityByUserTbl = new HashSet<ColumnVisibilityByUserTbl>();
            this.CommentReactionsTbl = new HashSet<CommentReactionsTbl>();
            this.CommentsTbl = new HashSet<CommentsTbl>();
            this.FilesTbl = new HashSet<FilesTbl>();
            this.LogTbl = new HashSet<LogTbl>();
            this.MainTicketTbl = new HashSet<MainTicketTbl>();
            this.MainTicketTbl1 = new HashSet<MainTicketTbl>();
            this.MainTicketTbl2 = new HashSet<MainTicketTbl>();
            this.MainTicketTbl3 = new HashSet<MainTicketTbl>();
            this.NotificationTbl = new HashSet<NotificationTbl>();
            this.StatusLogTbl = new HashSet<StatusLogTbl>();
            this.TicketHistoryTbl = new HashSet<TicketHistoryTbl>();
            this.TicketJiraTbl = new HashSet<TicketJiraTbl>();
            this.UserEmojiUsageTbl = new HashSet<UserEmojiUsageTbl>();
            this.UserFilterTbl = new HashSet<UserFilterTbl>();
            this.UserFollowerGroupListTbl = new HashSet<UserFollowerGroupListTbl>();
            this.UserFollowerGroupTbl = new HashSet<UserFollowerGroupTbl>();
            this.UserMailOptionTbl = new HashSet<UserMailOptionTbl>();
            this.UserRoleTbl = new HashSet<UserRoleTbl>();
            this.UserUnitTbl = new HashSet<UserUnitTbl>();
            this.WatcherGroupTbl = new HashSet<WatcherGroupTbl>();
            this.WatchersTbl = new HashSet<WatchersTbl>();
        }
    
        public int Id { get; set; }
        public string Registration { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string UserGuid { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public string yetkiTalebi { get; set; }
        public Nullable<int> talepAdedi { get; set; }
        public Nullable<int> PageLength { get; set; }
        public string JiraUsername { get; set; }
        public string JiraPassword { get; set; }
        public Nullable<bool> NotUser { get; set; }
        public string userName { get; set; }
        public Nullable<bool> AutoAssign { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityReactionsTbl> ActivityReactionsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColumnVisibilityByUserTbl> ColumnVisibilityByUserTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentReactionsTbl> CommentReactionsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentsTbl> CommentsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilesTbl> FilesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogTbl> LogTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTicketTbl> MainTicketTbl3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationTbl> NotificationTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusLogTbl> StatusLogTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketHistoryTbl> TicketHistoryTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketJiraTbl> TicketJiraTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEmojiUsageTbl> UserEmojiUsageTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFilterTbl> UserFilterTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFollowerGroupListTbl> UserFollowerGroupListTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFollowerGroupTbl> UserFollowerGroupTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMailOptionTbl> UserMailOptionTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleTbl> UserRoleTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserUnitTbl> UserUnitTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WatcherGroupTbl> WatcherGroupTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WatchersTbl> WatchersTbl { get; set; }
    }
}
