//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserUnitTbl
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UnitId { get; set; }
    
        public virtual UnitTbl UnitTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
