//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFilterTbl
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FilterSQLQuery { get; set; }
        public string FilterName { get; set; }
        public string FilterJsonQuery { get; set; }
        public string PageName { get; set; }
        public Nullable<int> FilterOrder { get; set; }
    
        public virtual UserTbl UserTbl { get; set; }
    }
}
