//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalenderDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceLogTbl
    {
        public int Id { get; set; }
        public string logText { get; set; }
        public string className { get; set; }
        public string functionName { get; set; }
        public string UserInfo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string type { get; set; }
    }
}
